services:

  postgres:
    image: postgres:16
    container_name: users-management-postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: crud_usuarios

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d crud_usuarios"]
      interval: 10s
      timeout: 5s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: users-management-app

    ports:
      - "8080:8080"

    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: crud_usuarios
      DB_USERNAME: postgres
      DB_PASSWORD: postgres123

      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: 587
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_FROM_ADDRESS: ${SMTP_USERNAME}
      SMTP_FROM_NAME: Gestion de Usuarios

    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: